import React, { createContext, useContext, useState, useEffect } from 'react';

// ─── Translations ───────────────────────────────────────
const translations: Record<string, Record<string, string>> = {
  ar: {
    // Nav & General
    home: 'الرئيسية',
    about: 'عن الجماعة',
    news: 'أخبار الجماعة',
    services: 'الخدمات الرقمية',
    projects: 'مشاريع وأنشطة',
    announcements: 'الإعلانات',
    documents: 'الوثائق',
    contact: 'اتصل بنا',
    employeePortal: 'فضاء الموظف',
    langSwitch: 'Français',
    quickLinks: 'روابط سريعة',
    projectsFooter: 'مشاريع',
    contactUs: 'اتصل بنا',
    aboutLink: 'عن الجماعة',
    eServices: 'الخدمات الإلكترونية',
    latestNews: 'آخر الأخبار',
    announcementsLink: 'الإعلانات والطلبات',
    devProjects: 'مشاريع التهيئة',
    greenSpaces: 'الفضاءات الخضراء',
    lighting: 'الإنارة العمومية',
    infrastructure: 'البنية التحتية',
    privacy: 'سياسة الخصوصية',
    terms: 'شروط الاستخدام',
    sitemap: 'خريطة الموقع',
    copyright: '© 2024 الجماعة الترابية - جميع الحقوق محفوظة',
    communeName: 'الجماعة الترابية',
    communeCity: 'مدينة العرائش',
    footerDesc: 'البوابة الرسمية للجماعة الترابية، نهدف من خلالها إلى تقريب الخدمات من المواطنين وتكريس مبدأ الإدارة الرقمية والشفافية.',
    address: 'شارع محمد الخامس، العرائش',
    
    // Landing Page
    heroTitle: 'مرحباً بكم في الموقع الرسمي للجماعة',
    heroSubtitle: 'خدمات إلكترونية للمواطنة وخدمة المواطنين',
    discoverMore: 'اكتشف المزيد',
    searchPlaceholder: 'ابحث عن وثيقة، خدمة، إعلان...',
    searchBtn: 'بحث',
    searchSuggestionsHeader: 'نتائج البحث في الخدمات، الوثائق، والإعلانات',
    serviceDocTitle: 'تحميل الوثائق',
    serviceDigitalTitle: 'الخدمات الرقمية',
    serviceAnnouncementsTitle: 'إعلانات الجماعة',
    serviceProjectsTitle: 'مشاريع وأنشطة',
    serviceAboutTitle: 'عن الجماعة',
    serviceDesc: 'اطلع على كافة التفاصيل والمعلومات المتعلقة بـ',
    more: 'المزيد',
    newsTitle: 'آخر أخبار ومستجدات الجماعة',
    viewAll: 'مشاهدة الكل',
    newsBadge: 'مستجدات',
    newsItemTitle: 'تثمين الواجهة البحرية للعرائش ضمن مشاريع التنمية الترابية',
    newsItemDesc: 'تعزيز جاذبية المدينة سياحياً واقتصادياً من خلال تطوير الواجهة البحرية وتوفير فضاءات عمومية حديثة تلبي تطلعات الساكنة...',
    newsItem2Title: 'إطلاق برنامج ترميم وصيانة المعالم التاريخية بمدينة العرائش',
    newsItem2Desc: 'في إطار الحفاظ على التراث المعماري العريق، تم إطلاق برنامج شامل لترميم وصيانة المعالم التاريخية بالمدينة...',
    newsItem3Title: 'مهرجان العرائش الدولي للثقافة والفنون في دورته العاشرة',
    newsItem3Desc: 'تحتضن مدينة العرائش فعاليات الدورة العاشرة من المهرجان الدولي للثقافة والفنون بمشاركة محلية ودولية واسعة...',
    serviceType: 'خدمة:',
    docType: 'وثيقة:',
    civilStatus: 'شواهد الحالة المدنية',
    buildingPermit: 'طلب رخصة التعمير',
    orgChart: 'الهيكل التنظيمي للجماعة',

    // Dashboard General
    dashboard: 'لوحة التحكم',
    logout: 'تسجيل الخروج',
    welcome: 'مرحباً',
    settings: 'الإعدادات',
    profile: 'ملفي الشخصي',
    hrManagement: 'إدارة الموارد البشرية',
    employees: 'الموظفون',
    addEmployee: 'إضافة موظف',
    rolesPermissions: 'الأدوار والصلاحيات',
    adminStatus: 'الحالة الإدارية',
    gradesScale: 'الدرجات والسلم',
    promotionsTransfers: 'الترقيات والتنقلات',
    performanceEval: 'تقييم الأداء',
    evalHistory: 'تاريخ التقييمات',
    careerPath: 'المسار المهني',
    salaries: 'الأجور والتعويضات',
    leaveManagement: 'إدارة العطل',
    docsNotifications: 'الوثائق والإشعارات',
    overview: 'نظرة عامة',
    talentManagement: 'إدارة المواهب',
    administrativeActs: 'القرارات الإدارية',
    intelReports: 'الذكاء والتقارير',
    operations: 'العمليات',
    adminDocuments: 'الوثائق الإدارية',
    systemHealth: 'اختبار الجودة',
    
    // Health Service
    healthService: 'مصلحة الصحة',
    healthDesc: 'تدبير الاستشارات الطبية والمتابعة الصحية للموظفين.',
    newConsultation: 'استشارة جديدة',
    consultationsDay: 'الاستشارات (اليوم)',
    followedAgents: 'الموظفون المتابعون',
    validatedAptitudes: 'الكفاءات المصادق عليها',
    queueAppointments: 'لائحة الانتظار والمواعيد',
    searchPatient: 'بحث عن مريض...',
    patient: 'المريض',
    type: 'النوع',
    service: 'المصلحة',
    lastVisit: 'آخر زيارة',
    status: 'الحالة',
    completed: 'منتهية',
    inProgress: 'في طور المعالجة',
    pending: 'في الانتظار',
    motif: 'سبب الاستشارة',
    annualConsultation: 'استشارة سنوية',
    vaccination: 'تلقيح',
    minorUrgency: 'حالة مستعجلة طفيفة',
    administrator: 'المشرف العام',
    viewProfile: 'عرض الملف الشخصي',
    fetchError: 'خطأ في جلب البيانات',
    saveError: 'خطأ في الحفظ',
    deleteConfirm: 'هل أنت متأكد من الحذف؟',
    deleteSuccess: 'تم الحذف بنجاح',
    prepPdf: 'جاري تحضير الملف...',
    downloaded: 'تم التحميل',
    installConfirm: 'هل أنت متأكد من اعتماد هذا القرار؟',
    installing: 'جاري الاعتماد...',
    installSuccess: 'تم الاعتماد بنجاح',
    installError: 'فشل الاعتماد',
    newAct: 'إنشاء قرار جديد',
    totalActs: 'إجمالي القرارات',
    installedActs: 'قرارات معتمدة',
    draftActs: 'مسودات قيد المعالجة',
    beneficiary: 'المعني بالأمر',
    actType: 'نوع القرار',
    version: 'الإصدار',
    edits: 'تعديلات',
    filter: 'تصفية',
    noActsFound: 'لا توجد قرارات حالياً',
    installer: 'اعتماد',
    installed: 'معتمد',
    validated: 'مصادق عليه',
    draft: 'مسودة',
    matricule: 'رقم التأجير',

    // Candidate Auth
    candidatePortal: 'فضاء المترشح',
    createCandidateAccount: 'إنشاء حساب مترشح',
    candidateInfoDesc: 'أدخل معلوماتك للتسجيل في منصة التوظيف',
    enterCandidateCode: 'المرجو إدخال رمز المترشح الخاص بك',
    candidateCodeLabel: 'رمز المترشح',
    candidateCodePlaceholder: 'مثال: CAND-A1B2C3',
    loginBtn: 'تسجيل الدخول',
    registerBtn: 'تسجيل',
    noAccount: 'ليس لديك حساب؟',
    hasAccount: 'لديك حساب مسبقاً؟',
    firstName: 'الاسم الشخصي',
    lastName: 'الاسم العائلي',
    cin: 'رقم البطاقة الوطنية (CIN)',
    email: 'البريد الإلكتروني',
    back: 'الرجوع',
    loginSuccess: 'تم تسجيل الدخول بنجاح',
    loginError: 'رمز المترشح غير صحيح',
    registerSuccess: 'تم إنشاء الحساب! تحقق من بريدك الإلكتروني للحصول على الرمز',
    invalidData: 'بيانات غير صالحة',
    registerError: 'خطأ أثناء إنشاء الحساب، المرجو التأكد من البيانات',
    demoCodePrefix: '(Demo) الرمز الخاص بك هو:',

    // Public: About
    aboutTitle: 'عن الجماعة',
    aboutBriefTitle: 'نبذة عن الجماعة',
    aboutP1: 'تعتبر الجماعة الترابية لمدينة العرائش من أهم المؤسسات المحلية التي تسهر على تدبير الشأن العام المحلي، وتقديم الخدمات الأساسية للمواطنين في مجالات البنية التحتية، التعمير، الصحة، والثقافة.',
    aboutP2: 'نعمل جاهدين من أجل تحسين جودة الحياة لساكنة المدينة من خلال مشاريع تنموية مستدامة، وتبني التكنولوجيا الحديثة لتقريب الإدارة من المواطن وتسهيل المساطر الإدارية.',
    presidentWord: 'كلمة رئيس الجماعة',
    presidentQuote: 'إن التزامنا اتجاه ساكنة هذه المدينة العريقة يضعنا أمام مسؤولية كبيرة للنهوض بكل القطاعات الحيوية. نحن نؤمن بأن الحكامة الجيدة والشفافية هما أساس النجاح، وندعو كافة المواطنين للمشاركة الفعالة في بناء مستقبل مدينتنا.',
    presidentTitle: 'رئيس المجلس الجماعي',

    // Public: Services
    servicesTitle: 'الخدمات الإلكترونية',
    servicesSubtitle: 'نقدم لكم مجموعة من الخدمات الإلكترونية لتسهيل مساطركم الإدارية دون الحاجة للتنقل',
    serviceCivilStatus: 'شواهد الحالة المدنية',
    serviceCivilStatusDesc: 'طلب عقود الازدياد والنسخ الكاملة للحالة المدنية عبر الإنترنت.',
    serviceUrbanism: 'رخص التعمير',
    serviceUrbanismDesc: 'إيداع وتتبع طلبات رخص البناء والتعمير والموافقة عليها رقمياً.',
    serviceAdminCert: 'الشواهد الإدارية',
    serviceAdminCertDesc: 'طلب مختلف الشواهد الإدارية التي تدخل في اختصاصات الجماعة.',
    serviceTaxes: 'الجبايات المحلية',
    serviceTaxesDesc: 'الاطلاع على الجبايات المحلية وأدائها بطريقة آمنة وسريعة.',
    serviceTracking: 'تتبع الطلبات',
    serviceTrackingDesc: 'تتبع وضعية ملفاتكم المودعة لدى مختلف مصالح الجماعة.',
    serviceComplaints: 'الشكايات والمقترحات',
    serviceComplaintsDesc: 'إيداع الشكايات المتعلقة بمصالح الجماعة وتتبع معالجتها.',
    accessService: 'ولوج الخدمة',

    // Public: News & Projects
    allNews: 'جميع الأخبار',
    projectsTitle: 'مشاريع الجماعة',
    projectsSubtitle: 'اكتشف أهم المشاريع التنموية والاجتماعية التي تسهر عليها الجماعة',
    currentProjects: 'مشاريع في طور الإنجاز',
    completedProjects: 'مشاريع منتهية',

    // Public: Contact
    contactTitle: 'اتصل بنا',
    contactSubtitle: 'نحن هنا للإجابة على تساؤلاتكم واستفساراتكم',
    fullName: 'الاسم الكامل',
    subject: 'الموضوع',
    message: 'الرسالة',
    sendBtn: 'إرسال الرسالة',
    contactInfo: 'معلومات الاتصال',
    workingHours: 'ساعات العمل',
    monFri: 'الاثنين - الجمعة: 8:30 صباحاً - 4:30 مساءً',

    // Candidate Portal
    candidateDashboard: 'لوحة تحكم المترشح',
    openConcours: 'المباريات المفتوحة',
    myApplications: 'ترشيحاتي',
    myProfile: 'ملفي الشخصي',
    activeApplications: 'الترشيحات النشطة',
    availableConcours: 'المباريات المتاحة',
    acceptedApplications: 'الترشيحات المقبولة',
    recentActivities: 'الأنشطة الأخيرة',
    noRecentActivity: 'لا توجد أنشطة أخيرة للعرض.',
    exploreOpportunities: 'استكشاف الفرص',
    searchConcours: 'بحث عن مباراة أو مصلحة...',
    filters: 'تصفية',
    noConcoursFound: 'لم يتم العثور على أي مباراة',
    noConcoursDesc: 'لا توجد حالياً أي مباراة مفتوحة تطابق بحثك. عد لاحقاً!',
    details: 'تفاصيل',
    apply: 'ترشح',
    alreadyApplied: 'تم الترشح مسبقاً',
    concoursClosed: 'المباراة مغلقة',
    applicationStatus: 'حالة الترشيح',
    appliedOn: 'تاريخ الترشيح',
    closingDate: 'تاريخ الإغلاق',
    generalInfo: 'معلومات عامة',
    editInfo: 'تعديل المعلومات',
    diplomas: 'المسار والشهادات',
    noDiplomas: 'لم يتم إدخال أي شهادة.',
    addDiploma: 'أضف مسارك الأكاديمي لتعزيز ترشيحك.',
    myCV: 'سيرتي الذاتية',
    uploadCV: 'اسحب سيرتك الذاتية هنا',
    pdfFormat: 'صيغة PDF (حد أقصى 5MB)',
    lastUpdated: 'آخر تحديث في',

    // RH Admin
    employeeManagement: 'إدارة الموظفين',
    searchEmployee: 'بحث عن موظف...',
    employeeName: 'اسم الموظف',
    role: 'الدور',
    grade: 'الدرجة',
    hiringDate: 'تاريخ التوظيف',
    actions: 'الإجراءات',
    edit: 'تعديل',
    delete: 'حذف',
    hrReports: 'التقارير الإدارية',

    // Generic UI
    save: 'حفظ',
    cancel: 'إلغاء',
    add: 'إضافة',
    confirm: 'تأكيد',
    search: 'بحث',
    loading: 'جاري التحميل...',
    noData: 'لا توجد بيانات متاحة',
    success: 'تمت العملية بنجاح',
    error: 'حدث خطأ ما',
    
    // Employee/RH Fields
    phone: 'الهاتف',
    department: 'المصلحة',
    jobTitle: 'المسمى الوظيفي',
    startDate: 'تاريخ البدء',
    endDate: 'تاريخ الانتهاء',
    amount: 'المبلغ',
    reason: 'السبب',
    description: 'الوصف',
    category: 'الفئة',
    step: 'الرتبة',
    level: 'السلم',
    document: 'الوثيقة',
    download: 'تحميل',
    print: 'طباعة',
    showAll: 'عرض الكل',
    previous: 'السابق',
    next: 'التالي',
    viewDetails: 'عرض التفاصيل',
    quickAccess: 'الولوج السريع',
    active: 'نشط',
    onLeave: 'في عطلة',
    inactive: 'غير نشط',
    yesterday: 'أمس',
    last48h: 'آخر 48 ساعة',
    statut: 'الحالة',
    systemOk: 'النظام يعمل',
    hoursAgo: 'منذ {n} ساعة',
    career: 'المسار المهني',
    reportsAndStats: 'التقارير والإحصائيات',
    hrAnalysisDesc: 'تحليل معمق وقيادة الموارد البشرية.',
    exportReport: 'تصدير التقرير',
    sixMonths: '6 أشهر',
    twelveMonths: '12 شهر',
    totalStaff: 'العدد الإجمالي',
    recruits: 'التوظيفات',
    payroll: 'كتلة الأجور',
    attendanceRate: 'معدل الحضور',
    staffEvolution: 'تطور الموظفين',
    currentSemesterProjection: 'توقعات السداسي الحالي',
    breakdownByCorps: 'التوزيع حسب الهيئة',
    agentDistribution: 'توزيع الأعوان',
    monthlyRecruitments: 'التوظيفات الشهرية',
    annualDetails: 'تفاصيل سنوية',
    flashAnalysis: 'تحاليل سريعة',
    genderParity: 'المناصفة',
    averageAge: 'متوسط العمر',
    turnover: 'معدل الدوران',
    viewFullAudit: 'عرض التدقيق الكامل',
    years: 'سنوات',
    activeAgents: 'أعوان نشطون',
    last6Months: 'آخر 6 أشهر',
    dhPerMonth: 'درهم في الشهر',
    annualAverage: 'المعدل السنوي',
    recruitmentManagement: 'تدبير التوظيف',
    recruitmentDesc: 'تتبع المباريات، الترشيحات وإدماج الموظفين الجدد.',
    launchConcours: 'إطلاق مباراة',
    candidatesMonth: 'المترشحون (الشهر)',
    openPositions: 'المناصب الشاغرة',
    avgTime: 'متوسط الوقت',
    pendingApplications: 'الترشيحات في انتظار المعالجة',
    searchCandidate: 'البحث عن مترشح...',
    candidate: 'المترشح',
    targetPosition: 'المنصب المطلوب',
    submissionDate: 'تاريخ الإيداع',
    interview: 'مقابلة',
    new: 'جديد',
    rejected: 'مرفوض',
    settingsDesc: 'قم بتخصيص مساحة عملك وإدارة تفضيلاتك.',
    appearance: 'المظهر',
    security: 'الأمان',
    system: 'النظام',
    visualCustomization: 'التخصيص البصري',
    visualCustomizationDesc: 'تطبق التغييرات فوراً على التطبيق بأكمله',
    colorTheme: 'سمة اللون',
    displayDensity: 'كثافة العرض',
    accountInfo: 'معلومات الحساب',
    accountInfoDesc: 'بيانات الاتصال وتفضيلات حسابك الإداري',
    professionalEmail: 'البريد الإلكتروني المهني',
    interfaceLanguage: 'لغة الواجهة',
    accountSecurity: 'أمان الحساب',
    accountSecurityDesc: 'احمِ وصولك إلى بيانات الموارد البشرية الحساسة',
    twoFactorAuth: 'المصادقة الثنائية (2FA)',
    twoFactorAuthDesc: 'تضيف طبقة أمان عبر الرسائل القصيرة أو التطبيق',
    changePassword: 'تغيير كلمة المرور',
    lastModified: 'آخر تغيير',
    trainingAndDev: 'التكوين والتطوير',
    trainingDesc: 'تتبع تعزيز القدرات والتكوين المستمر للموظفين.',
    newTraining: 'تكوين جديد',
    plannedTrainings: 'تكوينات مبرمجة',
    successRate: 'معدل النجاح',
    trainingCatalogue: 'دليل التكوينات',
    trainingRequests: 'طلبات التكوين',
    manageRequests: 'تدبير الطلبات',
    trainingGuide: 'دليل التكوين',
    trainingGuideDesc: 'راجع خطة التكوين السنوية 2025 لتوجيه فرقك بشكل أفضل.',
    downloadPDF: 'تحميل PDF',
    planned: 'مبرمج',
    agentsInscribed: 'أعوان مسجلون',
    confirmed: 'مؤكد',
    vetService: 'المصلحة البيطرية',
    vetDesc: 'تدبير البياطرة والتدخلات الصحية بجماعة العرائش.',
    newIntervention: 'تدخل جديد',
    activeVets: 'بياطرة نشطون',
    interventionsMonth: 'التدخلات (الشهر)',
    nonConformities: 'عدم المطابقة',
    vetTeam: 'الفريق البيطري',
    interventionsAndInspections: 'التدخلات والتفتيش',
    conforming: 'مطابق',
    nonConforming: 'غير مطابق',
    interventionType: 'نوع التدخل',
    result: 'النتيجة',
    interventionsPerMonth: 'تدخلات/الشهر',
    careerManagement: 'تدبير المسار المهني',
    careerDesc: 'تتبع التطورات، الترقيات والمسارات المهنية للموظفين.',
    promotionPlan: 'مخطط الترقي 2025',
    promotionDesc: 'راجع معايير الاستحقاق واللوائح التوقعية للجان الإدارية المتساوية الأعضاء المقبلة.',
    viewLists: 'عرض اللوائح',
    practicalGuide: 'دليل عملي',
    medalsAndDistinctions: 'الأوسمة والتكريمات',
    recognitionDesc: 'الاعتراف بالالتزام والأقدمية',
    medalsManagementDesc: 'تدبير ملفات الترشيح للأوسمة الشرفية وأوسمة الشغل لموظفي الجماعة.',
    openSession: 'فتح دورة 2025',
    documentManagement: 'تدبير الوثائق',
    documentDesc: 'أرشيف وتوليد الوثائق الإدارية للموظفين.',
    generateDocument: 'توليد وثيقة',
    categories: 'الفئات',
    workCertificates: 'شهادات العمل',
    nominationDecisions: 'قرارات التعيين',
    gradingSheets: 'أوراق التنقيط',
    medicalRecords: 'الملفات الطبية',
    recentDocuments: 'الوثائق الأخيرة',
    searchDocument: 'البحث عن وثيقة...',
    documentName: 'اسم الوثيقة',
    agent: 'الموظف',
    signed: 'موقع',
    salaryCertificate: 'شهادة الأجرة',
    recrutement: 'التوظيف',
    nomination: 'التعيين',
    titularisation: 'الترسيم',
    notation: 'التنقيط السنوي',
    avancement: 'الترقية',
    reclassement: 'إعادة الترتيب',
    saveAndPrint: 'حفظ وطباعة',
    actSavedSuccess: 'تم حفظ القرار بنجاح وجاري التحميل',
    selectEmployeeError: 'المرجو اختيار الموظف أولاً',
    concours: 'المباراة',
    nameLabel: 'الاسم',
    emailLabel: 'البريد الإلكتروني',
    roleLabel: 'الدور',
    requestLeave: 'طلب عطلة',
    noLeaveRequests: 'لا توجد طلبات عطل حاليا.',
    noSalaryData: 'لا توجد بيانات أجور.',
    netSalary: 'صافي الراتب',
    paymentDate: 'تاريخ الدفع',
    communeLarache: 'جماعة العرائش',
    notifications: 'الإشعارات',
    notificationsDesc: 'إدارة التنبيهات وإشعارات النظام',
    markAllRead: 'تحديد الكل كمقروء',
    upToDate: 'أنت على اطلاع دائم!',
    noNotifications: 'لا توجد إشعارات جديدة حالياً.',
    notifDeleted: 'تم حذف الإشعار',
    allMarkedRead: 'تم تحديد كل الإشعارات كمقروءة',
    loginPageTitle: 'بوابة الجماعة',
    loginPageSubtitle: 'خدمات رقمية حديثة وآمنة في خدمة مواطني العرائش',
    loginTitle: 'مرحباً',
    loginSubtitle: 'تسجيل الدخول إلى فضاؤكم الشخصي',
    usernameOrEmail: 'البريد الإلكتروني أو اسم المستخدم',
    usernameOrEmailPlaceholder: 'أدخل البريد الإلكتروني أو اسم المستخدم',
    passwordLabel: 'كلمة المرور',
    passwordPlaceholder: 'أدخل كلمة المرور',
    rememberMe: 'تذكرني',
    forgotPassword: 'نسيت كلمة المرور؟',
    orLoginWith: 'أو تسجيل الدخول بواسطة',
    candidateSpace: 'فضاء المترشح',
    contactAdmin: 'اتصل بالمسؤول',
    backToHome: 'الرجوع للخلف',
    allRightsReserved: 'جميع الحقوق محفوظة © 2024 الجماعة الترابية',
    communeDesc: 'الجماعة الترابية',
    futureCity: 'مدينة المستقبل',
    registerTitle: 'إنشاء حساب',
    registerSubtitle: 'انضم إلى المنصة الرقمية للجماعة.',
    cinMatricule: 'رقم البطاقة الوطنية / رقم التسجيل',
    emailProPerso: 'البريد الإلكتروني المهني / الشخصي',
    password: 'كلمة المرور',
    alreadyRegistered: 'مسجل بالفعل؟',
    loginHere: 'سجل دخولك هنا',
    createAccount: 'إنشاء حسابي',
    medicalDashboard: 'لوحة تحكم مصلحة الصحة',
    totalPatients: 'إجمالي المرضى',
    appointmentsToday: 'المواعيد اليوم',
    followUpCases: 'الحالات قيد المتابعة',
    medicalCertificates: 'الشواهد الطبية',
    upcomingAppointments: 'المواعيد القادمة',
    viewAllAppointments: 'عرض جميع المواعيد',
    viewAllCases: 'عرض جميع الحالات',
    newMedicalFile: 'ملف طبي جديد',
    newDiagnosis: 'تشخيص جديد',
    medicalCertificate: 'شهادة طبية',
    newAppointment: 'موعد جديد',
    recentNotifications: 'آخر الإشعارات',
    viewAllNotifications: 'عرض جميع الإشعارات',
    recentDiagnosisNotes: 'آخر التشخيصات والملاحظات',
    viewAllDiagnosis: 'عرض جميع التشخيصات',
    high: 'عالية',
    medium: 'متوسطة',
    low: 'منخفضة',
    vetDashboard: 'لوحة تحكم مصلحة البيطرة',
    totalAnimals: 'إجمالي الحيوانات',
    activeHealthCases: 'الحالات الصحية النشطة',
    completedVaccinations: 'التلقيحات المنجزة',
    certificatesIssued: 'الشهادات الصادرة',
    addAnimal: 'إضافة حيوان جديد',
    registerVaccination: 'تسجيل تلقيح جديد',
    issueVetCertificate: 'إصدار شهادة بيطرية',
    registerHealthCase: 'تسجيل حالة صحية',
    searchAnimal: 'بحث عن حيوان',
    recentHealthCases: 'الحالات الصحية الأخيرة',
    animalHealthStats: 'إحصائيات الصحة الحيوانية',
    viewMoreStats: 'عرض المزيد من الإحصائيات',
    monthlyPayroll: 'كتلة الأجور الشهرية',
    totalDeductions: 'إجمالي الاقتطاعات',
    salaryBase: 'الراتب الأساسي',
    deductions: 'الاقتطاعات',
    netPay: 'صافي الأجر',
    downloadRegistry: 'تحميل كشف الأجور العام',
    officialActivity: 'نشاط رسمي',
    administrative: 'إداري',
    cultural: 'ثقافي',
    environment: 'بيئة',
    readMore: 'اقرأ المزيد',
    featuredNews: 'خبر رئيسي',
    latestUpdates: 'آخر المستجدات',
    newsItem4Title: 'تحديثات جديدة في نظام تدبير الجبايات المحلية',
    newsItem4Desc: 'في إطار التحول الرقمي للجماعة، تم إطلاق منصة جديدة لتسهيل أداء الرسوم والجبايات المحلية بطريقة إلكترونية آمنة...',
    newsItem5Title: 'حملة نظافة واسعة النطاق بالأحياء الهامشية للمدينة',
    newsItem5Desc: 'بتعاون مع شركة التدبير المفوض وفعاليات المجتمع المدني، تم إطلاق حملة نظافة شاملة تهدف إلى تحسين جودة الحياة بالمنطقة...',
    newsItem6Title: 'انطلاق أشغال بناء المركز الثقافي الجديد بمدينة العرائش',
    newsItem6Desc: 'مشروع ثقافي ضخم يهدف إلى تعزيز البنية التحتية الثقافية وتوفير فضاءات للإبداع والشباب...',
    activeCandidacies: 'الترشيحات النشطة',
    exploreContests: 'استكشف المباريات',
    submitNewCandidacy: 'تقديم ترشيح جديد',
    faq: 'الأسئلة الشائعة',
    myCandidacies: 'ترشيحاتي',
    openContests: 'المباريات المفتوحة',
    candidacyManagement: 'إدارة الترشيحات',
    help: 'مساعدة',
    welcomeRecruitment: 'مرحباً بك في منصة التوظيف الخاصة بمدينة العرائش',
    noContestsAvailable: 'لا توجد مباريات متاحة حالياً',
    noRecentActivities: 'لا توجد أنشطة حديثة',
    viewAllActivities: 'عرض جميع الأنشطة',
    viewAllConcours: 'عرض جميع المباريات',
    deadline: 'آخر أجل للترشيح',
    contest: 'المباراة',
    publishDate: 'تاريخ النشر',
    operation: 'العملية',
    date: 'التاريخ',
  },
  fr: {
    // ... (rest of the code)
    // ... (rest of the code)
    // ... (rest of the code)
    // ... (rest of the code)
    // ... (rest of the code)
    // ... (rest of the code)
    // Nav & General
    home: 'Accueil',
    about: 'À propos',
    news: 'Actualités',
    services: 'Services numériques',
    projects: 'Projets & Activités',
    announcements: 'Annonces',
    documents: 'Documents',
    contact: 'Contact',
    employeePortal: 'Espace Employé',
    langSwitch: 'العربية',
    quickLinks: 'Liens rapides',
    projectsFooter: 'Projets',
    contactUs: 'Contactez-nous',
    aboutLink: 'À propos',
    eServices: 'Services en ligne',
    latestNews: 'Dernières nouvelles',
    announcementsLink: 'Annonces & Appels',
    devProjects: 'Projets d\'aménagement',
    greenSpaces: 'Espaces verts',
    lighting: 'Éclairage public',
    infrastructure: 'Infrastructure',
    privacy: 'Politique de confidentialité',
    terms: 'Conditions d\'utilisation',
    sitemap: 'Plan du site',
    copyright: '© 2024 Commune Territoriale - Tous droits réservés',
    communeName: 'Commune Territoriale',
    communeCity: 'Ville de Larache',
    footerDesc: 'Portail officiel de la commune territoriale. Nous visons à rapprocher les services des citoyens et à consacrer le principe de l\'administration numérique et de la transparence.',
    address: 'Avenue Mohammed V, Larache',
    
    // Landing Page
    heroTitle: 'Bienvenue sur le site officiel de la commune',
    heroSubtitle: 'Services électroniques pour les citoyens',
    discoverMore: 'En savoir plus',
    searchPlaceholder: 'Rechercher un document, un service, une annonce...',
    searchBtn: 'Rechercher',
    searchSuggestionsHeader: 'Résultats de recherche pour les services, documents et annonces',
    serviceDocTitle: 'Téléchargement de documents',
    serviceDigitalTitle: 'Services numériques',
    serviceAnnouncementsTitle: 'Annonces communales',
    serviceProjectsTitle: 'Projets & Activités',
    serviceAboutTitle: 'À propos de la commune',
    serviceDesc: 'Consultez tous les détails et informations concernant',
    more: 'Plus',
    newsTitle: 'Dernières nouvelles et mises à jour de la commune',
    viewAll: 'Voir tout',
    newsBadge: 'Actualités',
    newsItemTitle: 'Lancement des travaux d\'aménagement des espaces verts au centre-ville',
    newsItemDesc: 'Dans le cadre du programme de développement urbain de la commune, le lancement des travaux d\'aménagement et de décoration des jardins publics et des places a été donné aujourd\'hui...',
    newsItem2Title: 'Restauration des monuments historiques de Larache',
    newsItem2Desc: 'Un programme ambitieux a été lancé pour la sauvegarde du patrimoine architectural de notre ville historique...',
    newsItem3Title: 'Festival International des Arts de Larache',
    newsItem3Desc: 'La 10ème édition du festival a débuté avec une participation record d\'artistes locaux et internationaux...',
    officialActivity: 'Activité Officielle',
    administrative: 'Administratif',
    cultural: 'Culturel',
    environment: 'Environnement',
    readMore: 'Lire la suite',
    featuredNews: 'À la une',
    latestUpdates: 'Dernières mises à jour',
    newsItem4Title: 'Nouvelles mises à jour du système de gestion des taxes locales',
    newsItem4Desc: 'Dans le cadre de la transformation numérique de la commune, une nouvelle plateforme a été lancée pour faciliter le paiement...',
    newsItem5Title: 'Vaste campagne de nettoyage dans les quartiers périphériques',
    newsItem5Desc: 'En collaboration avec la société de gestion déléguée et la société civile, une campagne de nettoyage complète a été lancée...',
    newsItem6Title: 'Début des travaux de construction du nouveau centre culturel',
    newsItem6Desc: 'Un projet culturel majeur visant à renforcer les infrastructures culturelles et à offrir des espaces de création...',
    activeCandidacies: 'Candidatures Actives',
    availableConcours: 'Concours Disponibles',
    acceptedCandidacies: 'Candidatures Acceptées',
    latestAvailableConcours: 'Derniers Concours Disponibles',
    recentActivities: 'Mes Activités Récentes',
    exploreContests: 'Explorer les Concours',
    submitNewCandidacy: 'Soumettre une Candidature',
    viewDetails: 'Voir les Détails',
    faq: 'FAQ',
    myCandidacies: 'Mes Candidatures',
    openContests: 'Concours Ouverts',
    candidacyManagement: 'Gestion des Candidatures',
    help: 'Aide',
    dashboard: 'Tableau de bord',
    welcomeRecruitment: 'Bienvenue sur la plateforme de recrutement de Larache',
    noContestsAvailable: 'Aucun concours disponible pour le moment',
    noRecentActivities: 'Aucune activité récente',
    viewAllActivities: 'Voir toutes les activités',
    viewAllConcours: 'Voir tous les concours',
    actions: 'Actions',
    status: 'Statut',
    deadline: 'Délai',
    contest: 'Concours',
    publishDate: 'Date de Publication',
    operation: 'Opération',
    date: 'Date',
    serviceType: 'Service:',
    docType: 'Document:',
    civilStatus: 'État Civil',
    buildingPermit: 'Permis de construire',
    orgChart: 'Organigramme',
    allRightsReserved: 'Tous droits réservés © 2024 Commune Territoriale',
    communeDesc: 'Commune Territoriale',
    futureCity: 'Ville du Futur',
    quickAccess: 'Accès rapides',
    overview: 'Aperçu',
    active: 'Actif',
    onLeave: 'En congé',
    inactive: 'Inactif',
    yesterday: 'Hier',
    last48h: 'Dernières 48h',
    statut: 'Statut',
    systemOk: 'Système OK',
    hoursAgo: 'Il y a {n}h',
    career: 'Carrière',
    reportsAndStats: 'Rapports & Statistiques',
    hrAnalysisDesc: 'Analyse approfondie et pilotage des ressources humaines.',
    exportReport: 'Exporter le Rapport',
    sixMonths: '6 mois',
    twelveMonths: '12 mois',
    totalStaff: 'Effectif Total',
    recruits: 'Recrutements',
    payroll: 'Masse Salariale',
    attendanceRate: 'Taux de Présence',
    staffEvolution: 'Évolution de l\'Effectif',
    currentSemesterProjection: 'Projection sur le semestre actuel',
    breakdownByCorps: 'Répartition par Corps',
    agentDistribution: 'Distribution des agents',
    monthlyRecruitments: 'Recrutements Mensuels',
    annualDetails: 'Détails annuels',
    flashAnalysis: 'Analyses Flash',
    genderParity: 'Parité H/F',
    averageAge: 'Moyenne d\'âge',
    turnover: 'Turn-over',
    viewFullAudit: 'Voir l\'audit complet',
    years: 'ans',
    activeAgents: 'Agents actifs',
    last6Months: 'Derniers 6 mois',
    dhPerMonth: 'DH par mois',
    annualAverage: 'Moyenne annuelle',
    recruitmentManagement: 'Gestion du Recrutement',
    recruitmentDesc: 'Suivi des concours, candidatures et intégration des nouveaux agents.',
    launchConcours: 'Lancer un Concours',
    candidatesMonth: 'Candidats (Mois)',
    openPositions: 'Postes à pourvoir',
    avgTime: 'Temps moyen',
    pendingApplications: 'Candidatures en attente',
    searchCandidate: 'Rechercher un candidat...',
    candidate: 'Candidat',
    targetPosition: 'Poste visé',
    submissionDate: 'Date dépôt',
    interview: 'Entretien',
    new: 'Nouveau',
    rejected: 'Rejeté',
    visualCustomization: 'Personnalisation visuelle',
    visualCustomizationDesc: 'Les changements s\'appliquent instantanément sur toute l\'application',
    colorTheme: 'Thème de couleur',
    displayDensity: 'Densité d\'affichage',
    accountInfo: 'Informations du compte',
    accountInfoDesc: 'Coordonnées et préférences de votre compte administratif',
    professionalEmail: 'Email professionnel',
    interfaceLanguage: 'Langue de l\'interface',
    accountSecurity: 'Sécurité du compte',
    accountSecurityDesc: 'Protégez votre accès aux données sensibles du RH',
    twoFactorAuth: 'Authentification à deux facteurs (2FA)',
    twoFactorAuthDesc: 'Ajoute une couche de sécurité via SMS ou App',
    changePassword: 'Changer le mot de passe',
    lastModified: 'Dernière modification',
    trainingAndDev: 'Formation & Développement',
    trainingDesc: 'Suivi du renforcement des capacités et de la formation continue des agents.',
    newTraining: 'Nouvelle Formation',
    plannedTrainings: 'Formations planifiées',
    successRate: 'Taux de réussite',
    trainingCatalogue: 'Catalogue des Formations',
    trainingRequests: 'Demandes de Formation',
    manageRequests: 'Gérer les demandes',
    trainingGuide: 'Guide de Formation',
    trainingGuideDesc: 'Consultez le plan de formation annuel 2025 pour mieux orienter vos équipes.',
    downloadPDF: 'Télécharger le PDF',
    planned: 'Planifiée',
    agentsInscribed: 'agents inscrits',
    confirmed: 'Confirmé',
    vetService: 'Service Vétérinaire',
    vetDesc: 'Gestion des vétérinaires et des interventions de la commune de Larache.',
    newIntervention: 'Nouvelle Intervention',
    activeVets: 'Vétérinaires actifs',
    interventionsMonth: 'Interventions (Mois)',
    nonConformities: 'Non conformités',
    vetTeam: 'Équipe vétérinaire',
    interventionsAndInspections: 'Interventions & Inspections',
    conforming: 'Conforme',
    nonConforming: 'Non Conforme',
    interventionType: 'Type d\'intervention',
    result: 'Résultat',
    interventionsPerMonth: 'interventions/mois',
    careerManagement: 'Gestion de Carrière',
    careerDesc: 'Suivi des évolutions, promotions et parcours professionnels des agents.',
    promotionPlan: 'Plan de Promotion 2025',
    promotionDesc: 'Consultez les critères d\'éligibilité et les listes prévisionnelles pour les prochaines commissions paritaires.',
    viewLists: 'Voir les listes',
    practicalGuide: 'Guide pratique',
    medalsAndDistinctions: 'Médailles & Distinctions',
    recognitionDesc: 'Reconnaissance de l\'engagement et de l\'ancienneté',
    medalsManagementDesc: 'Gérez les dossiers de candidatures aux distinctions honorifiques et médailles du travail pour les agents de la commune.',
    openSession: 'Ouvrir la session 2025',
    documentManagement: 'Gestion Documentaire',
    documentDesc: 'Archive et génération de documents administratifs pour les agents.',
    generateDocument: 'Générer un document',
    categories: 'Catégories',
    workCertificates: 'Attestations de travail',
    nominationDecisions: 'Décisions de nomination',
    gradingSheets: 'Feuilles de notation',
    medicalRecords: 'Dossiers médicaux',
    administrativeActs: 'Actes Administratifs',
    talentManagement: 'Talents',
    intelReports: 'Intelligence',
    operations: 'Opérations',
    adminDocuments: 'Documents Administratifs',
    systemHealth: 'Test Qualité',
    recentDocuments: 'Documents Récents',
    searchDocument: 'Rechercher un document...',
    documentName: 'Nom du document',
    agent: 'Agent',
    signed: 'Signé',
    salaryCertificate: 'Attestation de Salaire',
    recrutement: 'Recrutement',
    nomination: 'Nomination',
    titularisation: 'Titularisation',
    notation: 'Notation Annuelle',
    avancement: 'Avancement',
    reclassement: 'Reclassement',
    saveAndPrint: 'Enregistrer & Imprimer',
    actSavedSuccess: 'Acte enregistré avec succès, téléchargement en cours',
    fetchError: 'Erreur lors de la récupération des données',
    selectEmployeeError: 'Veuillez sélectionner un employé',
    concours: 'Concours',
    nameLabel: 'Nom',
    emailLabel: 'Email',
    roleLabel: 'Rôle',
    requestLeave: 'Demander un congé',
    noLeaveRequests: 'Aucune demande de congé pour le moment.',
    noSalaryData: 'Aucune donnée de salaire.',
    netSalary: 'Salaire net',
    paymentDate: 'Date de paiement',
    communeLarache: 'Commune de Larache',
    notifications: 'Notifications',
    notificationsDesc: 'Gérez vos alertes et notifications système',
    markAllRead: 'Tout marquer comme lu',
    upToDate: 'Vous êtes à jour !',
    noNotifications: 'Aucune nouvelle notification pour le moment.',
    notifDeleted: 'Notification supprimée',
    allMarkedRead: 'Toutes les notifications marquées comme lues',
    loginPageTitle: 'Portail de la Commune',
    loginPageSubtitle: 'Services numériques modernes et sécurisés au service des citoyens de Larache',
    loginTitle: 'Bienvenue',
    loginSubtitle: 'Connectez-vous à votre espace personnel',
    usernameOrEmail: 'Email ou nom d\'utilisateur',
    usernameOrEmailPlaceholder: 'Entrez votre email ou nom d\'utilisateur',
    passwordLabel: 'Mot de passe',
    passwordPlaceholder: 'Entrez votre mot de passe',
    rememberMe: 'Se souvenir de moi',
    forgotPassword: 'Mot de passe oublié ?',
    orLoginWith: 'OU SE CONNECTER AVEC',
    candidateSpace: 'Espace Candidat',
    contactAdmin: 'Contactez l\'administrateur',
    backToHome: 'Retour',
    medicalDashboard: 'Tableau de bord Médical',
    totalPatients: 'Total Patients',
    appointmentsToday: 'Rendez-vous aujourd\'hui',
    followUpCases: 'Cas suivis',
    medicalCertificates: 'Certificats médicaux',
    upcomingAppointments: 'Prochains rendez-vous',
    viewAllAppointments: 'Voir tous les rendez-vous',
    viewAllCases: 'Voir tous les cas',
    newMedicalFile: 'Nouveau dossier médical',
    newDiagnosis: 'Nouveau diagnostic',
    medicalCertificate: 'Certificat médical',
    newAppointment: 'Nouveau rendez-vous',
    recentNotifications: 'Dernières notifications',
    viewAllNotifications: 'Voir toutes les notifications',
    recentDiagnosisNotes: 'Derniers diagnostics et notes',
    viewAllDiagnosis: 'Voir tous les diagnostics',
    high: 'Haute',
    medium: 'Moyenne',
    low: 'Basse',
    vetDashboard: 'Tableau de bord Vétérinaire',
    totalAnimals: 'Total Animaux',
    activeHealthCases: 'Cas sanitaires actifs',
    completedVaccinations: 'Vaccinations effectuées',
    certificatesIssued: 'Certificats délivrés',
    addAnimal: 'Ajouter un animal',
    registerVaccination: 'Enregistrer une vaccination',
    issueVetCertificate: 'Délivrer un certificat vétérinaire',
    registerHealthCase: 'Enregistrer un cas sanitaire',
    searchAnimal: 'Rechercher un animal',
    recentHealthCases: 'Derniers cas sanitaires',
    animalHealthStats: 'Statistiques santé animale',
    viewMoreStats: 'Voir plus de statistiques',
    monthlyPayroll: 'Masse Salariale Mensuelle',
    totalDeductions: 'Total Déductions',
    salaryBase: 'Salaire de Base',
    deductions: 'Déductions',
    netPay: 'Salaire Net',
    downloadRegistry: 'Télécharger le registre général',
    administrator: 'Administrateur',
    viewProfile: 'Voir le profil',
    saveError: 'Erreur de sauvegarde',
    deleteConfirm: 'Êtes-vous sûr de vouloir supprimer ?',
    deleteSuccess: 'Supprimé avec succès',
    prepPdf: 'Préparation du PDF...',
    downloaded: 'Téléchargé',
    installConfirm: 'Confirmer l\'installation de cet acte ?',
    installing: 'Installation en cours...',
    installSuccess: 'Acte installé avec succès',
    installError: 'Erreur d\'installation',
    newAct: 'Nouveau Décision',
    totalActs: 'Total Décisions',
    installedActs: 'Décisions Installées',
    draftActs: 'Brouillons',
    beneficiary: 'Bénéficiaire',
    actType: 'Type Acte',
    version: 'Version',
    edits: 'Edits',
    filter: 'Filtrer',
    noActsFound: 'Aucun acte trouvé',
    installer: 'Installer',
    installed: 'Installé',
    validated: 'Validé',
    draft: 'Brouillon',
    matricule: 'Matricule',
  }
};

interface LangContextType {
  lang: string;
  setLang: (l: string) => void;
  t: (key: string) => string;
}

const LangContext = createContext<LangContextType | undefined>(undefined);

export const LangProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLangState] = useState<string>(() => {
    return localStorage.getItem('site-lang') || 'ar';
  });

  const setLang = (l: string) => {
    setLangState(l);
    localStorage.setItem('site-lang', l);
  };

  const t = (key: string): string => {
    return translations[lang]?.[key] || key;
  };

  useEffect(() => {
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  }, [lang]);

  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
};

export const useLang = () => {
  const context = useContext(LangContext);
  if (context === undefined) {
    throw new Error('useLang must be used within a LangProvider');
  }
  return context;
};
